"""without s

Revision ID: 006d51f25491
Revises: f322fd50d4b1
Create Date: 2023-08-01 21:00:05.841047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006d51f25491'
down_revision = 'f322fd50d4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
