"""datetime

Revision ID: 1a03e329d39a
Revises: 006d51f25491
Create Date: 2023-08-01 21:17:28.359242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a03e329d39a'
down_revision = '006d51f25491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
